name: Malware Scan
on: [push, pull_request]

jobs:
  clamav-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ClamAV Scan
        uses: nigel-daly/clamav-scan@v2
        with:
          scan-dir: '.'
